export const CATEGORIES_ACTION_TYPE = {
  FATCH_CATEGORIES_START: 'category/FATCH_CATEGORIES_START',
  FATCH_CATEGORIES_SUCCESS: 'category/FATCH_CATEGORIES_SUCCESS',
  FATCH_CATEGORIES_FAILED: 'category/FATCH_CATEGORIES_FAILED',
};
